# Generated by Django 3.1.1 on 2020-10-15 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201014_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('email', 'Email'), ('github', 'Github'), ('vk', 'VK')], default='email', max_length=50),
        ),
    ]
