# Generated by Django 3.1.1 on 2020-09-21 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20200921_0307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='rules',
            new_name='house_rules',
        ),
    ]
