# Generated by Django 3.1.1 on 2021-05-14 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_boookedday'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoookedDay',
            new_name='BookedDay',
        ),
    ]
